title: El_photography
url:  SamD97.github.io
baseurl: /el_photo

author: Disha Patel
description: Discovering the world with my vision.

defaults:
  - scope:
      path: "assets/images/pondi"
    values:
      image: true


markdown: kramdown
kramdown:
  input: GFM